version: '3.5'
services:
  taskforce.tasks.postgres:
    image: postgres:14-alpine
    container_name: taskforce.tasks.postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: test
      POSTGRES_DB: taskforce-tasks
    ports:
      - 5432:5432
    volumes:
      - taskforce.postgres.tasks:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d test" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - taskforce.tasks

  taskforce.tasks.pgadmin:
    image: dpage/pgadmin4
    container_name: taskforce.tasks.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "keks@htmlacademy.local"
      PGADMIN_DEFAULT_PASSWORD: "test"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    networks:
      - taskforce.tasks

volumes:
  taskforce.postgres.tasks:

networks:
  taskforce.tasks:
    driver: bridge
